
fridaResults = crawlFolder('clear');
frida2Results = crawlFolder('fog');

figure;
plot(1:size(fridaResults, 2), fridaResults(1,:), 'or', ...
    1:size(fridaResults, 2), fridaResults(2,:), 'og', ...
    1:size(fridaResults, 2), fridaResults(3,:), 'ob', ...
    1:size(fridaResults, 2), fridaResults(4,:), 'ok', ...
    1:size(fridaResults, 2), fridaResults(5,:), 'om');
figure;
plot(1:size(frida2Results, 2), frida2Results(1,:), 'or', ...
    1:size(frida2Results, 2), frida2Results(2,:), 'og', ...
    1:size(frida2Results, 2), frida2Results(3,:), 'ob', ...
    1:size(frida2Results, 2), frida2Results(4,:), 'ok', ...
    1:size(frida2Results, 2), frida2Results(5,:), 'om');