
fridaResults = crawlFolder('frida');
frida2Results = crawlFolder('frida2');

figure;
plot(1:size(fridaResults, 2), fridaResults(1,:), '*r-', ...
    1:size(fridaResults, 2), fridaResults(2,:), '*g-', ...
    1:size(fridaResults, 2), fridaResults(3,:), '*b-', ...
    1:size(fridaResults, 2), fridaResults(4,:), '*k-', ...
    1:size(fridaResults, 2), fridaResults(5,:), '*m-');
figure;
plot(1:size(frida2Results, 2), frida2Results(1,:), '*r-', ...
    1:size(frida2Results, 2), frida2Results(2,:), '*g-', ...
    1:size(frida2Results, 2), frida2Results(3,:), '*b-', ...
    1:size(frida2Results, 2), frida2Results(4,:), '*k-', ...
    1:size(frida2Results, 2), frida2Results(5,:), '*m-');